server:
  port: 8075


fanwei:
  oa:
    hrmUrl: http://oa.qunje.com:88/services/HrmService?wsdl
    hrmTargetNamespace: http://localhost/services/HrmService



fs:
  appId: FSAID_1319599
  appSecret: 0d89f64d5e8548d0b6cb923f14c4f7c5
  permanentCode: D99DBF885DCF101DCCC707042209DE23
  token: 01705ddef3ac437c9ef5d32626b51208
  encodingAesKey: YjBlOTAyMjIzMTJmNGVjOTkyNmE5MDEzZjM1NzE2Njc
  authorize.url: www.fxiaoke.com




logging:
  level:
    com:
      qunje: DEBUG
    root: INFO


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa_crm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
